In [1]:
import os
import warnings
import tqdm
import pandas as pd
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

In [2]:
%load_ext autoreload
%autoreload 2
import socceraction.spadl as spadl
import socceraction.vaep.features as fs
import socceraction.vaep.labels as lab

In [3]:
datafolder = "../data-fifa"
spadl_h5 = os.path.join(datafolder, "spadl-statsbomb.h5")
features_h5 = os.path.join(datafolder, "features.h5")
labels_h5 = os.path.join(datafolder, "labels.h5")

In [4]:
games = pd.read_hdf(spadl_h5, "games")
print("nb of games:", len(games))

nb of games: 64

In [5]:
games

,game_id,season_id,competition_id,competition_stage,game_day,game_date,home_team_id,away_team_id,home_score,away_score,venue,referee,competition_name,country_name,competition_gender,season_name,home_team_name,away_team_name
0,7548,3,43,Group Stage,2,2018-06-22 14:00:00,781,795,2,0,Saint-Petersburg Stadium,Björn Kuipers,FIFA World Cup,International,male,2018,Brazil,Costa Rica
1,7578,3,43,Group Stage,1,2018-06-15 14:00:00,774,783,0,1,\tEkaterinburg Arena,Björn Kuipers,FIFA World Cup,International,male,2018,Egypt,Uruguay
2,7553,3,43,Group Stage,2,2018-06-23 17:00:00,791,794,1,2,\tRostov Arena,Milorad Mažić,FIFA World Cup,International,male,2018,South Korea,Mexico
3,7544,3,43,Group Stage,2,2018-06-20 17:00:00,783,799,1,0,\tRostov Arena,Clément Turpin,FIFA World Cup,International,male,2018,Uruguay,Saudi Arabia
4,7536,3,43,Group Stage,1,2018-06-18 17:00:00,782,798,3,0,\tOlimpiyskiy Stadion Fisht,Janny Sikazwe,FIFA World Cup,International,male,2018,Belgium,Panama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,7540,3,43,Group Stage,2,2018-06-19 20:00:00,796,774,3,1,Saint-Petersburg Stadium,Enrique Cáceres,FIFA World Cup,International,male,2018,Russia,Egypt
60,8652,3,43,Quarter-finals,5,2018-07-07 20:00:00,796,785,2,2,\tOlimpiyskiy Stadion Fisht,Sandro Ricci,FIFA World Cup,International,male,2018,Russia,Croatia
61,7563,3,43,Group Stage,3,2018-06-26 16:00:00,776,771,0,0,Stadion Luzhniki,Sandro Ricci,FIFA World Cup,International,male,2018,Denmark,France
62,7556,3,43,Group Stage,2,2018-06-24 17:00:00,778,787,2,2,\tEkaterinburg Arena,Gianluca Rocchi,FIFA World Cup,International,male,2018,Japan,Senegal
63,7559,3,43,Group Stage,3,2018-06-25 16:00:00,799,774,2,1,Volgograd Arena,Wilmar Alexander Roldán Pérez,FIFA World Cup,International,male,2018,Saudi Arabia,Egypt

In [6]:
xfns = [
    fs.actiontype,
    fs.actiontype_onehot,
    fs.bodypart,
    fs.bodypart_onehot,
    fs.result,
    fs.result_onehot,
    fs.goalscore,
    fs.startlocation,
    fs.endlocation,
    fs.movement,
    fs.space_delta,
    fs.startpolar,
    fs.endpolar,
    fs.team,
    fs.time,
    fs.time_delta
]

for game in tqdm.tqdm(list(games.itertuples()), desc=f"Generating and storing features in {features_h5}"):
    actions = pd.read_hdf(spadl_h5, f"actions/game_{game.game_id}")
    print(actions.shape)
    gamestates = fs.gamestates(spadl.add_names(actions), 3)
    gamestates = fs.play_left_to_right(gamestates, game.home_team_id)
    
    X = pd.concat([fn(gamestates) for fn in xfns], axis=1)
    X.to_hdf(features_h5, f"game_{game.game_id}")

Generating and storing features in ../data-fifa\features.h5:   3%|▎         | 2/64 [00:00<00:05, 11.38it/s]

(2211, 14)
(2164, 14)
(1894, 14)

Generating and storing features in ../data-fifa\features.h5:   6%|▋         | 4/64 [00:00<00:05, 10.94it/s]

(2230, 14)
(2052, 14)
(2071, 14)

Generating and storing features in ../data-fifa\features.h5:  12%|█▎        | 8/64 [00:00<00:05, 10.97it/s]

(2053, 14)
(1940, 14)
(1792, 14)

Generating and storing features in ../data-fifa\features.h5:  16%|█▌        | 10/64 [00:00<00:04, 10.94it/s]

(2312, 14)
(2270, 14)
(1952, 14)

Generating and storing features in ../data-fifa\features.h5:  22%|██▏       | 14/64 [00:01<00:04, 11.07it/s]

(1901, 14)
(1963, 14)
(1936, 14)

Generating and storing features in ../data-fifa\features.h5:  25%|██▌       | 16/64 [00:01<00:04, 11.09it/s]

(1948, 14)
(2502, 14)
(1763, 14)

Generating and storing features in ../data-fifa\features.h5:  31%|███▏      | 20/64 [00:01<00:04, 10.91it/s]

(1872, 14)
(2014, 14)
(2047, 14)

Generating and storing features in ../data-fifa\features.h5:  34%|███▍      | 22/64 [00:01<00:03, 10.97it/s]

(1606, 14)
(1937, 14)
(1946, 14)

Generating and storing features in ../data-fifa\features.h5:  41%|████      | 26/64 [00:02<00:03, 11.17it/s]

(2038, 14)
(1834, 14)
(1894, 14)

Generating and storing features in ../data-fifa\features.h5:  44%|████▍     | 28/64 [00:02<00:03, 11.05it/s]

(2092, 14)
(1874, 14)
(2154, 14)

Generating and storing features in ../data-fifa\features.h5:  50%|█████     | 32/64 [00:02<00:02, 11.31it/s]

(1870, 14)
(1920, 14)
(1724, 14)

Generating and storing features in ../data-fifa\features.h5:  53%|█████▎    | 34/64 [00:03<00:02, 11.46it/s]

(1806, 14)
(2131, 14)
(2917, 14)

Generating and storing features in ../data-fifa\features.h5:  59%|█████▉    | 38/64 [00:03<00:02, 11.45it/s]

(1910, 14)
(1754, 14)
(1989, 14)

Generating and storing features in ../data-fifa\features.h5:  62%|██████▎   | 40/64 [00:03<00:02, 11.43it/s]

(2211, 14)
(1919, 14)
(1810, 14)

Generating and storing features in ../data-fifa\features.h5:  69%|██████▉   | 44/64 [00:03<00:01, 11.38it/s]

(2124, 14)
(1561, 14)
(2159, 14)

Generating and storing features in ../data-fifa\features.h5:  72%|███████▏  | 46/64 [00:04<00:01, 10.68it/s]

(1897, 14)
(1858, 14)

Generating and storing features in ../data-fifa\features.h5:  75%|███████▌  | 48/64 [00:04<00:01, 10.14it/s]

(1630, 14)
(1836, 14)
(2055, 14)

Generating and storing features in ../data-fifa\features.h5:  78%|███████▊  | 50/64 [00:04<00:01,  9.88it/s]

(2291, 14)
(2305, 14)

Generating and storing features in ../data-fifa\features.h5:  84%|████████▍ | 54/64 [00:04<00:00, 10.24it/s]

(1820, 14)
(2288, 14)
(1868, 14)

Generating and storing features in ../data-fifa\features.h5:  88%|████████▊ | 56/64 [00:05<00:00, 10.64it/s]

(2099, 14)
(2211, 14)
(1971, 14)

Generating and storing features in ../data-fifa\features.h5:  91%|█████████ | 58/64 [00:05<00:00, 10.70it/s]

(2512, 14)
(1850, 14)

Generating and storing features in ../data-fifa\features.h5:  97%|█████████▋| 62/64 [00:05<00:00, 10.57it/s]

(2342, 14)
(2113, 14)
(1728, 14)

Generating and storing features in ../data-fifa\features.h5: 100%|██████████| 64/64 [00:05<00:00, 10.86it/s]

(2196, 14)

In [7]:
X

,type_id_a0,type_id_a1,type_id_a2,type_pass_a0,type_cross_a0,type_throw_in_a0,type_freekick_crossed_a0,type_freekick_short_a0,type_corner_crossed_a0,type_corner_short_a0,...,time_seconds_a0,time_seconds_overall_a0,period_id_a1,time_seconds_a1,time_seconds_overall_a1,period_id_a2,time_seconds_a2,time_seconds_overall_a2,time_delta_1,time_delta_2
0,0,0,0,True,False,False,False,False,False,False,...,0.0,0.0,1,0.0,0.0,1,0.0,0.0,0.0,0.0
1,21,0,0,False,False,False,False,False,False,False,...,1.0,1.0,1,0.0,0.0,1,0.0,0.0,1.0,1.0
2,0,21,0,True,False,False,False,False,False,False,...,1.0,1.0,1,1.0,1.0,1,0.0,0.0,0.0,1.0
3,21,0,21,False,False,False,False,False,False,False,...,2.0,2.0,1,1.0,1.0,1,1.0,1.0,1.0,1.0
4,0,21,0,True,False,False,False,False,False,False,...,3.0,3.0,1,2.0,2.0,1,1.0,1.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2191,0,9,7,True,False,False,False,False,False,False,...,2943.0,5643.0,2,2941.0,5641.0,2,2941.0,5641.0,2.0,2.0
2192,21,0,9,False,False,False,False,False,False,False,...,2944.0,5644.0,2,2943.0,5643.0,2,2941.0,5641.0,1.0,3.0
2193,0,21,0,True,False,False,False,False,False,False,...,2944.0,5644.0,2,2944.0,5644.0,2,2943.0,5643.0,0.0,1.0
2194,11,0,21,False,False,False,False,False,False,False,...,2945.0,5645.0,2,2944.0,5644.0,2,2944.0,5644.0,1.0,1.0
2195,0,11,0,True,False,False,False,False,False,False,...,3028.0,5728.0,2,2945.0,5645.0,2,2944.0,5644.0,83.0,84.0

In [8]:
yfns = [lab.scores, lab.concedes, lab.goal_from_shot]

for game in tqdm.tqdm(list(games.itertuples()), desc=f"Computing and storing labels in {labels_h5}"):
    actions = pd.read_hdf(spadl_h5, f"actions/game_{game.game_id}")   
    Y = pd.concat([fn(spadl.add_names(actions)) for fn in yfns], axis=1)
    Y.to_hdf(labels_h5, f"game_{game.game_id}")

Computing and storing labels in ../data-fifa\labels.h5: 100%|██████████| 64/64 [00:05<00:00, 12.58it/s]

In [9]:
Y

      scores  concedes  goal_from_shot
0      False     False           False
1      False     False           False
2      False     False           False
3      False     False           False
4      False     False           False
...      ...       ...             ...
2191    True     False           False
2192    True     False           False
2193    True     False           False
2194    True     False            True
2195   False     False           False

[2196 rows x 3 columns]